version: '3'

services:
  app:
    container_name: FastAPI
    build:
     context: .
     dockerfile: ./docker/Dockerfile
    volumes:
      - ./src/main.py:/var/www/html/main.py
      - ./pyproject.toml:/var/www/html/pyproject.toml
    ports:
      - "9004:9004"
    tty: true
    network_mode: "host"