[tool.poetry]
name = "takapisama-demo"
version = "1.1.14"
description = ""
authors = ["author name here"]

[tool.poetry.dependencies]
python = "3.8.13"
numpy = "^1.23.1"
pandas = "^1.4.3"
fastapi = "^0.79.0"
uvicorn = "^0.18.2"