FROM python:3.7
WORKDIR /var/www/html
RUN pip install fastapi uvicorn
#RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python && \
#    . $HOME/.poetry/env && \
#    poetry config virtualenvs.create false && \
#    poetry add numpy